CREATE TABLE PRODUCT_TYPE(
ID SERIAL PRIMARY KEY,
DESCRIPTION VARCHAR(255)
)



CREATE TABLE PRODUCTS(
ID SERIAL PRIMARY KEY,
DESCRIPTION VARCHAR(255),
BRAND VARCHAR(255),
TYPE INTEGER,
CONSTRAINT fk_type_product
   FOREIGN KEY(type) 
   	REFERENCES PRODUCT_TYPE(id)
)

CREATE TABLE PRODUCTS_INFO(
ID SERIAL PRIMARY KEY,
ID_PRODUCT INTEGER,
SIZE CHAR(2),
COLOR VARCHAR(255),
PRICE NUMERIC,
CONSTRAINT FK_PRODUCT_INFO
	FOREIGN KEY(ID_PRODUCT)
		REFERENCES PRODUCTS(ID)
)

INSERT INTO PRODUCT_TYPE (DESCRIPTION) VALUES ('Vestúario')
INSERT INTO PRODUCT_TYPE (DESCRIPTION) VALUES ('Acessório')
INSERT INTO PRODUCT_TYPE (DESCRIPTION) VALUES ('Cosmético')